// Generated by scripts/contract.py from frozen OpenAPI; do not edit.
// Required keys and snake_case preserved. ISO dates/date-times are strings.

export type ActivitySummary = {
  activity: string;
  record_count: number;
  observed_dates: number;
  duration_ms: number | null;
};

export type Baseline = {
  window_days: 7 | 14 | 30;
  window_start: string | null;
  window_end: string | null;
  anchor_date: string | null;
  includes_anchor: false;
  observed_days: number;
  required_days: number | null;
  average: number | null;
  difference: number | null;
  percentage_deviation: number | null;
  eligible: boolean | null;
  coverage_status: "full" | "partial" | "insufficient" | "unavailable";
};

export type Error = {
  code: "local_access_only" | "not_found" | "read_only" | "invalid_query" | "internal_error" | "snapshot_unavailable";
  message: string;
  retryable: boolean;
  request_id: string;
};

export type Freshness = {
  status: "unknown";
  days_since_latest_available_morning: number | null;
  may_be_out_of_date: boolean;
  collection_time_known: false;
};

export type Health = {
  status: "ok";
  schema_version: "v1";
};

export type Interpretation = {
  overall_state: "strong positive" | "strong negative" | "generally positive" | "generally negative" | "mixed" | "insufficient data";
  window_days: 14;
  signals: InterpretationSignals;
  reason_codes: Array<string>;
};

export type InterpretationSignals = {
  recovery_score: Signal;
  hrv_ms: Signal;
  resting_heart_rate_bpm: Signal;
  sleep_performance: Signal;
};

export type Metric = {
  value: number | null;
  unit: "ms" | "percent" | "bpm" | "breaths/min" | "count";
  origin: "whoop" | "derived";
  availability: "available" | "missing" | "pending" | "withheld";
  reason_codes: Array<string>;
};

export type Nap = {
  timing: Timing;
  actual_sleep: Metric;
};

export type Physiology = {
  metric: Metric;
  baselines: Array<Baseline>;
};

export type Signal = {
  state: "positive" | "negative" | "neutral" | "insufficient data";
  reason_codes: Array<string>;
};

export type SleepMetrics = {
  in_bed_ms: Metric;
  awake_ms: Metric;
  no_data_ms: Metric;
  light_ms: Metric;
  deep_ms: Metric;
  rem_ms: Metric;
  baseline_need_ms: Metric;
  sleep_debt_need_ms: Metric;
  recent_strain_need_ms: Metric;
  nap_adjustment_ms: Metric;
  performance_pct: Metric;
  efficiency_pct: Metric;
  consistency_pct: Metric;
  respiratory_rate: Metric;
  sleep_cycle_count: Metric;
  disturbance_count: Metric;
  actual_sleep_ms: Metric;
  restorative_sleep_ms: Metric;
  total_need_ms: Metric;
  actual_minus_need_ms: Metric;
  light_pct_actual_sleep: Metric;
  deep_pct_actual_sleep: Metric;
  rem_pct_actual_sleep: Metric;
  restorative_pct_actual_sleep: Metric;
  awake_pct_in_bed: Metric;
};

export type SleepReport = {
  report_date: string | null;
  status: "available" | "partial" | "unavailable" | "ambiguous";
  timing: Timing;
  metrics: SleepMetrics;
  quality_codes: Array<string>;
  naps: Array<Nap>;
  trends: SleepTrends;
};

export type SleepResponse = {
  schema_version: "v1";
  analysis_version: string;
  snapshot_id: string;
  generated_at: string;
  report_date: string | null;
  latest_available_morning: string | null;
  collection_freshness: Freshness;
  last_successful_sync_at: string | null;
  data: SleepReport;
};

export type SleepSummary = {
  status: "available" | "partial" | "unavailable" | "ambiguous";
  timing: Timing;
  actual_sleep: Metric;
  sleep_need: Metric;
  sleep_performance: Metric;
  sleep_efficiency: Metric;
};

export type SleepTrends = {
  actual_sleep: TrendReport;
  sleep_need: TrendReport;
  sleep_performance: TrendReport;
  sleep_efficiency: TrendReport;
  sleep_consistency: TrendReport;
  respiratory_rate: TrendReport;
  deep_sleep: TrendReport;
  rem_sleep: TrendReport;
  restorative_sleep: TrendReport;
};

export type Timing = {
  local_start: string | null;
  local_end: string | null;
  recorded_offset: string | null;
  recorded_interval_ms: number | null;
};

export type TodayPhysiology = {
  recovery_score: Physiology;
  hrv_ms: Physiology;
  resting_heart_rate_bpm: Physiology;
  sleep_performance: Physiology;
};

export type TodayReport = {
  latest_available_morning: string | null;
  physiology: TodayPhysiology;
  interpretation: Interpretation;
  last_sleep: SleepSummary;
  yesterday_training: TrainingSummary;
  quality_codes: Array<string>;
};

export type TodayResponse = {
  schema_version: "v1";
  analysis_version: string;
  snapshot_id: string;
  generated_at: string;
  report_date: string | null;
  latest_available_morning: string | null;
  collection_freshness: Freshness;
  last_successful_sync_at: string | null;
  data: TodayReport;
};

export type TrainingSummary = {
  availability: "available" | "missing";
  start_date: string | null;
  end_date: string | null;
  record_count: number | null;
  observed_dates: number | null;
  duration_ms: number | null;
  calendar_coverage: "unknown";
  activities: Array<ActivitySummary>;
};

export type TrendPoint = {
  report_date: string;
  recorded_offsets: Array<string>;
  metric: Metric;
};

export type TrendReport = {
  metric: "actual_sleep" | "sleep_need" | "sleep_performance" | "sleep_efficiency" | "sleep_consistency" | "respiratory_rate" | "deep_sleep" | "rem_sleep" | "restorative_sleep";
  anchor_date: string | null;
  window_days: 7 | 14 | 30 | null;
  daily_points: Array<TrendPoint>;
  prior_windows: Array<Baseline>;
};

export type TrendResponse = {
  schema_version: "v1";
  analysis_version: string;
  snapshot_id: string;
  generated_at: string;
  report_date: string | null;
  latest_available_morning: string | null;
  collection_freshness: Freshness;
  last_successful_sync_at: string | null;
  data: TrendReport;
};
