"""Project the frozen in-memory OpenAPI to static TS; never read repository data.

Run from any directory with the repository Python environment. No Node generator.
Default checks drift; --write refreshes only the two mobile contract artifacts.
Unsupported schema shapes fail loudly rather than producing permissive types.
"""
import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))
from api.app import create_app
from api.schemas import TodayResponse, SleepResponse, TrendResponse


def ts(schema):
    if '$ref' in schema:
        return schema['$ref'].rsplit('/', 1)[1]
    if 'const' in schema:
        return json.dumps(schema['const'])
    if 'enum' in schema:
        return ' | '.join(json.dumps(value) for value in schema['enum'])
    if 'anyOf' in schema:
        return ' | '.join(dict.fromkeys(ts(value) for value in schema['anyOf']))
    kind = schema.get('type')
    if kind == 'array':
        return f"Array<{ts(schema['items'])}>"
    if kind == 'object' and 'properties' in schema:
        required = set(schema.get('required', []))
        return '{\n' + ''.join(
            f'  {name}{"" if name in required else "?"}: {ts(value)};\n'
            for name, value in schema['properties'].items()) + '}'
    if kind in ('string', 'integer', 'number', 'boolean', 'null'):
        return {'integer': 'number'}.get(kind, kind)
    raise ValueError(f'Unsupported public schema shape: {kind}')


def artifacts():
    schema = create_app(object()).openapi()
    text = '// Generated by scripts/contract.py from frozen OpenAPI; do not edit.\n'
    text += '// Required keys and snake_case preserved. ISO dates/date-times are strings.\n\n'
    for name, value in sorted(schema['components']['schemas'].items()):
        text += f'export type {name} = {ts(value)};\n\n'
    fixture = (ROOT / 'tests/fixtures/api_v1_examples.json').read_text(encoding='utf-8')
    payload = json.loads(fixture)
    for key, model in [('today', TodayResponse), ('sleep', SleepResponse), ('trends', TrendResponse)]:
        model.model_validate(payload[key])
    return {'src/types/api-v1.ts': text.rstrip('\n') + '\n', 'src/api/fixtures/api_v1_examples.json': fixture}


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    for relative, content in artifacts().items():
        target = Path(__file__).resolve().parents[1] / relative
        if args.write:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding='utf-8', newline='\n')
        elif not target.exists() or target.read_text(encoding='utf-8') != content:
            raise SystemExit(f'Contract drift: {relative}')
    print('Frozen types and synthetic fixture match API V1.')
